"""add surname

Revision ID: 865692e699e6
Revises: f6eda7049057
Create Date: 2022-05-26 21:09:47.462143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865692e699e6'
down_revision = 'f6eda7049057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author_model', sa.Column('surname', sa.String(length=64), server_default='Default', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author_model', 'surname')
    # ### end Alembic commands ###
